In [1]:
# Import everything required
from sqlalchemy import create_engine

import pandas as pd
import numpy as np

census= pd.read_csv(r'census_city.csv')

census_pop= pd.DataFrame(census)

census_pop

from sqlalchemy import create_engine

engine = create_engine('sqlite://', echo=False)

In [2]:
#remove redundant 'city' in city names from census dataset
census_pop.loc[:,'City'] = census_pop.City.map(lambda x : x.replace('city', ''))

In [3]:
census_pop

census_pop.to_csv(r'census_pop.csv')

In [4]:
#read in prices data from zillow dataset
prices = pd.read_csv(r'Sale_Prices_City.csv')
prices

,Unnamed: 0,RegionID,RegionName,StateName,SizeRank,2008-03,2008-04,2008-05,2008-06,2008-07,...,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03
0,0,6181,New York,New York,1,NaN,NaN,NaN,NaN,NaN,...,563200.0,570500.0,572800.0,569900.0,560800.0,571500.0,575100.0,571700.0,568300.0,573600.0
1,1,12447,Los Angeles,California,2,507600.0,489600.0,463000.0,453100.0,438100.0,...,706800.0,711800.0,717300.0,714100.0,711900.0,718400.0,727100.0,738200.0,760200.0,NaN
2,2,39051,Houston,Texas,3,138400.0,135500.0,132200.0,131000.0,133400.0,...,209700.0,207400.0,207600.0,207000.0,211400.0,211500.0,217700.0,219200.0,223800.0,NaN
3,3,17426,Chicago,Illinois,4,325100.0,314800.0,286900.0,274600.0,268500.0,...,271500.0,266500.0,264900.0,265000.0,264100.0,264300.0,270000.0,281400.0,302900.0,309200.0
4,4,6915,San Antonio,Texas,5,130900.0,131300.0,131200.0,131500.0,131600.0,...,197100.0,198700.0,200200.0,200800.0,203400.0,203800.0,205400.0,205400.0,208300.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3723,3723,40400,Port Bolivar,Texas,3724,NaN,NaN,NaN,NaN,NaN,...,278400.0,254300.0,273200.0,286200.0,278100.0,285500.0,267200.0,302900.0,333700.0,330100.0
3724,3724,397820,Long Beach Township,New Jersey,3725,NaN,NaN,NaN,NaN,NaN,...,846300.0,912100.0,943700.0,897600.0,836000.0,839900.0,824100.0,839000.0,860600.0,NaN
3725,3725,37346,Beech Mountain,North Carolina,3726,NaN,NaN,NaN,NaN,NaN,...,191400.0,172700.0,195700.0,189500.0,166500.0,130900.0,139800.0,129400.0,124800.0,131000.0
3726,3726,34991,Corolla,North Carolina,3727,NaN,NaN,NaN,NaN,NaN,...,522400.0,521000.0,480000.0,430600.0,476400.0,560800.0,565400.0,514000.0,444200.0,NaN
3727,3727,52829,La Vernia,Texas,3728,NaN,NaN,NaN,NaN,NaN,...,337900.0,342900.0,358300.0,373100.0,375100.0,358600.0,356500.0,336700.0,340400.0,327000.0

In [5]:
# finding averages by year because data is broken down by month

prices_2010 = prices.iloc(axis=1)[[2,3,27,28,29,30,31,32,33,34,35,36,37,38]]
df = prices_2010.mean(axis=1)
avg_2010 = prices_2010.reset_index()

avg_2010['2010 Avg Price'] = df
avg_2010

0       457300.0
1       353725.0
2       134650.0
3       205200.0
4       131392.0
          ...
3723         NaN
3724         NaN
3725         NaN
3726         NaN
3727         NaN
Length: 3728, dtype: float64

In [7]:
#add new avg column to the final dataset
master_avg = avg_2010.iloc(axis=1)[[1,2,15]]

In [8]:
# finding averages by year because data is broken down by month

prices

prices_2011 = prices.iloc(axis=1)[[39,40,41,42,43,44,45,46,47,48,49,50]]

prices_2011

df2011 = prices_2011.mean(axis=1)
df2011

#add new avg column to the final dataset
master_avg.loc['2011 Avg Price'] = df2011

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

                         RegionName       StateName  2010 Avg Price
0                          New York        New York   457300.000000
1                       Los Angeles      California   353725.000000
2                           Houston           Texas   134650.000000
3                           Chicago        Illinois   205200.000000
4                       San Antonio           Texas   131391.666667
...                             ...             ...             ...
3724            Long Beach Township      New Jersey             NaN
3725                 Beech Mountain  North Carolina             NaN
3726                        Corolla  North Carolina             NaN
3727                      La Vernia           Texas             NaN
2011 Avg Price                  NaN             NaN             NaN

[3729 rows x 3 columns]

In [9]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2012 = prices.iloc(axis=1)[[51,52,53,54,55,56,57,58,59,60,61,62]]

prices_2012

df2012 = prices_2012.mean(axis=1)
df2012

master_avg.loc['2012 Avg Price'] = df2012

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

                    RegionName       StateName  2010 Avg Price
0                     New York        New York   457300.000000
1                  Los Angeles      California   353725.000000
2                      Houston           Texas   134650.000000
3                      Chicago        Illinois   205200.000000
4                  San Antonio           Texas   131391.666667
...                        ...             ...             ...
3725            Beech Mountain  North Carolina             NaN
3726                   Corolla  North Carolina             NaN
3727                 La Vernia           Texas             NaN
2011 Avg Price             NaN             NaN             NaN
2012 Avg Price             NaN             NaN             NaN

[3730 rows x 3 columns]

In [10]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2013 = prices.iloc(axis=1)[[63,64,65,66,67,68,69,70,71,72,73,74]]

prices_2013

df2013 = prices_2013.mean(axis=1)
df2013

master_avg.loc[:,'2013 Avg Price'] = df2013

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

                    RegionName       StateName  2010 Avg Price  2013 Avg Price
0                     New York        New York   457300.000000   483691.666667
1                  Los Angeles      California   353725.000000   443841.666667
2                      Houston           Texas   134650.000000   158116.666667
3                      Chicago        Illinois   205200.000000   211350.000000
4                  San Antonio           Texas   131391.666667   144908.333333
...                        ...             ...             ...             ...
3725            Beech Mountain  North Carolina             NaN             NaN
3726                   Corolla  North Carolina             NaN   500558.333333
3727                 La Vernia           Texas             NaN             NaN
2011 Avg Price             NaN             NaN             NaN             NaN
2012 Avg Price             NaN             NaN             NaN             NaN

[3730 rows x 4 columns]

In [11]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2014 = prices.iloc(axis=1)[[76,76,77,78,79,80,81,82,83,84,85,86]]

prices_2014

df2014 = prices_2014.mean(axis=1)
df2014

master_avg.loc[:,'2014 Avg Price'] = df2014

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,RegionName,StateName,2010 Avg Price,2013 Avg Price,2014 Avg Price
0,New York,New York,457300.000000,483691.666667,490233.333333
1,Los Angeles,California,353725.000000,443841.666667,459833.333333
2,Houston,Texas,134650.000000,158116.666667,168950.000000
3,Chicago,Illinois,205200.000000,211350.000000,239450.000000
4,San Antonio,Texas,131391.666667,144908.333333,154241.666667
...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN
3726,Corolla,North Carolina,NaN,500558.333333,478775.000000
3727,La Vernia,Texas,NaN,NaN,NaN
2011 Avg Price,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN

In [12]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2015 = prices.iloc(axis=1)[[87,88,89,90,91,92,93,94,95,96,97,98]]

prices_2015

df2015 = prices_2015.mean(axis=1)
df2015

master_avg.loc[:,'2015 Avg Price'] = df2015

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,RegionName,StateName,2010 Avg Price,2013 Avg Price,2014 Avg Price,2015 Avg Price
0,New York,New York,457300.000000,483691.666667,490233.333333,518291.666667
1,Los Angeles,California,353725.000000,443841.666667,459833.333333,493125.000000
2,Houston,Texas,134650.000000,158116.666667,168950.000000,170983.333333
3,Chicago,Illinois,205200.000000,211350.000000,239450.000000,236675.000000
4,San Antonio,Texas,131391.666667,144908.333333,154241.666667,164875.000000
...,...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN,NaN
3726,Corolla,North Carolina,NaN,500558.333333,478775.000000,453758.333333
3727,La Vernia,Texas,NaN,NaN,NaN,NaN
2011 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2016 = prices.iloc(axis=1)[[99,100,101,102,103,104,105,106,107,108,109,110]]

prices_2016

df2016 = prices_2016.mean(axis=1)
df2016

master_avg.loc[:,'2016 Avg Price'] = df2016

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,RegionName,StateName,2010 Avg Price,2013 Avg Price,2014 Avg Price,2015 Avg Price,2016 Avg Price
0,New York,New York,457300.000000,483691.666667,490233.333333,518291.666667,537025.000000
1,Los Angeles,California,353725.000000,443841.666667,459833.333333,493125.000000,530608.333333
2,Houston,Texas,134650.000000,158116.666667,168950.000000,170983.333333,180991.666667
3,Chicago,Illinois,205200.000000,211350.000000,239450.000000,236675.000000,219291.666667
4,San Antonio,Texas,131391.666667,144908.333333,154241.666667,164875.000000,171508.333333
...,...,...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN,NaN,NaN
3726,Corolla,North Carolina,NaN,500558.333333,478775.000000,453758.333333,428191.666667
3727,La Vernia,Texas,NaN,NaN,NaN,NaN,NaN
2011 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2017 = prices.iloc(axis=1)[[111,112,113,114,115,116,117,118,119,120,121,122]]

prices_2017

df2017 = prices_2017.mean(axis=1)
df2017

master_avg.loc[:,'2017 Avg Price'] = df2017

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,RegionName,StateName,2010 Avg Price,2013 Avg Price,2014 Avg Price,2015 Avg Price,2016 Avg Price,2017 Avg Price
0,New York,New York,457300.000000,483691.666667,490233.333333,518291.666667,537025.000000,542558.333333
1,Los Angeles,California,353725.000000,443841.666667,459833.333333,493125.000000,530608.333333,568141.666667
2,Houston,Texas,134650.000000,158116.666667,168950.000000,170983.333333,180991.666667,191100.000000
3,Chicago,Illinois,205200.000000,211350.000000,239450.000000,236675.000000,219291.666667,226908.333333
4,San Antonio,Texas,131391.666667,144908.333333,154241.666667,164875.000000,171508.333333,177775.000000
...,...,...,...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN,NaN,NaN,138080.000000
3726,Corolla,North Carolina,NaN,500558.333333,478775.000000,453758.333333,428191.666667,457908.333333
3727,La Vernia,Texas,NaN,NaN,NaN,NaN,NaN,306812.500000
2011 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2018 = prices.iloc(axis=1)[[123,124,125,126,127,128,129,130,131,132,133,134]]

prices_2018

df2018 = prices_2018.mean(axis=1)
df2018

master_avg.loc[:,'2018 Avg Price'] = df2018

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,RegionName,StateName,2010 Avg Price,2013 Avg Price,2014 Avg Price,2015 Avg Price,2016 Avg Price,2017 Avg Price,2018 Avg Price
0,New York,New York,457300.000000,483691.666667,490233.333333,518291.666667,537025.000000,542558.333333,555475.000000
1,Los Angeles,California,353725.000000,443841.666667,459833.333333,493125.000000,530608.333333,568141.666667,638983.333333
2,Houston,Texas,134650.000000,158116.666667,168950.000000,170983.333333,180991.666667,191100.000000,197275.000000
3,Chicago,Illinois,205200.000000,211350.000000,239450.000000,236675.000000,219291.666667,226908.333333,246716.666667
4,San Antonio,Texas,131391.666667,144908.333333,154241.666667,164875.000000,171508.333333,177775.000000,188141.666667
...,...,...,...,...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN,NaN,NaN,138080.000000,151358.333333
3726,Corolla,North Carolina,NaN,500558.333333,478775.000000,453758.333333,428191.666667,457908.333333,446225.000000
3727,La Vernia,Texas,NaN,NaN,NaN,NaN,NaN,306812.500000,327933.333333
2011 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# finding averages by year because data is broken down by month
#add new avg column to the final dataset
prices_2019 = prices.iloc(axis=1)[[135,136,137,138,139,140,141,142,143,145,146]]

prices_2019

df2019 = prices_2019.mean(axis=1)
df2019

master_avg.loc[:,'2019 Avg Price'] = df2019

master_avg

/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [17]:
#rename columns to match census dataset with zillow dataset
avgs = master_avg.rename(columns={"RegionName":"city", "StateName":"state"})
avgs.head()

#round numbers
rounded_avg = avgs.round(decimals = 2)

rounded_avg

,city,state,2010 Avg Price,2013 Avg Price,2014 Avg Price,2015 Avg Price,2016 Avg Price,2017 Avg Price,2018 Avg Price,2019 Avg Price
0,New York,New York,457300.00,483691.67,490233.33,518291.67,537025.00,542558.33,555475.00,566609.09
1,Los Angeles,California,353725.00,443841.67,459833.33,493125.00,530608.33,568141.67,638983.33,706027.27
2,Houston,Texas,134650.00,158116.67,168950.00,170983.33,180991.67,191100.00,197275.00,208700.00
3,Chicago,Illinois,205200.00,211350.00,239450.00,236675.00,219291.67,226908.33,246716.67,269990.91
4,San Antonio,Texas,131391.67,144908.33,154241.67,164875.00,171508.33,177775.00,188141.67,196954.55
...,...,...,...,...,...,...,...,...,...,...
3725,Beech Mountain,North Carolina,NaN,NaN,NaN,NaN,NaN,138080.00,151358.33,170963.64
3726,Corolla,North Carolina,NaN,500558.33,478775.00,453758.33,428191.67,457908.33,446225.00,484054.55
3727,La Vernia,Texas,NaN,NaN,NaN,NaN,NaN,306812.50,327933.33,353627.27
2011 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012 Avg Price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#read to csv the avgs for price
rounded_avg.to_csv(r'avg_prices.csv')

#read in population dataset that Max cleaned up - cleaning city & state names in SQL
population = pd.read_csv(r'Zillow_Population.csv')


pop = pd.DataFrame(population)


#remove space in 'state' in order to match across datasets

population['state'] = population['state'].str.strip()

#merge tw
pop_price = pd.merge(pop, rounded_avg, how= 'right', on=["city", "state"])

del pop_price['US_News_State_Overall_Rank']
del pop_price['Data_Scientist_Job_Postings']
del pop_price['Rank']
del pop_price['Average_Annual_Salary']
del pop_price['ZORI_2020-06']
del pop_price['Property_Crime_Rate']
del pop_price['US_News_Overall_Score']
del pop_price['Highest_Monthly_Avg_High_Temp']
del pop_price['Violent_Crime_Rate']
del pop_price['Avg_Annual_Rainfall']
del pop_price['Lowest_Monthly_Avg_High_Temp']
del pop_price['Est_2019_Population']
del pop_price['Estimates_Base']

pop_price = pop_price.rename(columns={"_2010" : "2010 Population",
                                      "_2011" : "2011 Population",
                                      "_2012" : "2012 Population",
                                      "_2013": "2013 Population",
                                     "_2014": "2014 Population",
                                     "_2015": "2015 Population",
                                     "_2016": "2016 Population",
                                     "_2017": "2017 Population",
                                     "_2018": "2018 Population",
                                     "_2019": "2019 Population"})

In [19]:
pop_price.to_csv(r'pop_price.csv')

pop_price.to_sql('pop_price', con=engine)

engine.execute("SELECT * FROM pop_price").fetchall()

[(0, 'New York', 'New York', 8190209.0, 8272948.0, 8346693.0, 8396091.0, 8433806.0, 8463049.0, 8469153.0, 8437478.0, 8390081.0, 8336817.0, 457300.0, 483691.67, 490233.33, 518291.67, 537025.0, 542558.33, 555475.0, 566609.09),
 (1, 'Los Angeles', 'California', 3795512.0, 3820876.0, 3851202.0, 3881622.0, 3909901.0, 3938568.0, 3963226.0, 3975788.0, 3977596.0, 3979576.0, 353725.0, 443841.67, 459833.33, 493125.0, 530608.33, 568141.67, 638983.33, 706027.27),
 (2, 'Chicago', 'Illinois', 2697477.0, 2708114.0, 2719141.0, 2725731.0, 2727066.0, 2724344.0, 2716723.0, 2711069.0, 2701423.0, 2693976.0, 205200.0, 211350.0, 239450.0, 236675.0, 219291.67, 226908.33, 246716.67, 269990.91),
 (3, 'Houston', 'Texas', 2100280.0, 2126032.0, 2161593.0, 2199391.0, 2241826.0, 2286908.0, 2309544.0, 2316750.0, 2318573.0, 2320268.0, 134650.0, 158116.67, 168950.0, 170983.33, 180991.67, 191100.0, 197275.0, 208700.0),
 (4, 'Phoenix', 'Arizona', 1449038.0, 1469796.0, 1499274.0, 1526491.0, 1555445.0, 1583690.0, 1612199.0, 1633560.0, 1654675.0, 1680992.0, 96675.0, 130908.33, 140141.67, 158608.33, 177425.0, 193991.67, 217108.33, 231663.64),
 (5, 'Philadelphia', 'Pennsylvania', 1528283.0, 1540466.0, 1551824.0, 1558313.0, 1565460.0, 1571065.0, 1576051.0, 1580601.0, 1583592.0, 1584064.0, 112116.67, 109616.67, 118716.67, 118850.0, 123408.33, 140625.0, 142633.33, 161136.36),
 (6, 'San Antonio', 'Texas', 1332299.0, 1357120.0, 1383075.0, 1408339.0, 1435456.0, 1464043.0, 1487843.0, 1511154.0, 1530016.0, 1547253.0, 131391.67, 144908.33, 154241.67, 164875.0, 171508.33, 177775.0, 188141.67, 196954.55),
 (7, 'San Diego', 'California', 1305906.0, 1319592.0, 1336776.0, 1355320.0, 1375831.0, 1387323.0, 1402089.0, 1412621.0, 1421917.0, 1423851.0, 346383.33, 419300.0, 450341.67, 476616.67, 504141.67, 543366.67, 586733.33, 599781.82),
 (8, 'San Jose', 'California', 954940.0, 970369.0, 983530.0, 1001279.0, 1014273.0, 1025980.0, 1030242.0, 1032335.0, 1028020.0, 1021795.0, 451350.0, 582575.0, 641625.0, 704808.33, 760125.0, 841975.0, 1015750.0, 945400.0),
 (9, 'Austin', 'Texas', 806164.0, 828459.0, 854482.0, 875003.0, 901170.0, 921114.0, 939447.0, 951553.0, 962469.0, 978908.0, 222358.33, 254541.67, 271683.33, 294775.0, 317516.67, 336816.67, 354350.0, 372172.73),
 (10, 'Jacksonville', 'Florida', 823114.0, 829609.0, 837013.0, 842735.0, 852494.0, 865836.0, 880520.0, 892025.0, 902437.0, 911507.0, 97366.67, 83475.0, 82375.0, 89891.67, 108425.0, 127475.0, 141800.0, 161718.18),
 (11, 'Columbus', 'Ohio', 790943.0, 800607.0, 812740.0, 827797.0, 841673.0, 854950.0, 866894.0, 881694.0, 890869.0, 898553.0, 100550.0, 101600.0, 114266.67, 126516.67, 130283.33, 139325.0, 146925.0, 157909.09),
 (12, 'Charlotte', 'North Carolina', 738444.0, 754829.0, 773264.0, 792047.0, 807400.0, 825668.0, 843117.0, 860002.0, 872514.0, 885708.0, 138550.0, 157308.33, 168675.0, 179925.0, 185566.67, 187350.0, 214858.33, 233118.18),
 (13, 'San Francisco', 'California', 805505.0, 815650.0, 828876.0, 839572.0, 850750.0, 863010.0, 871512.0, 878040.0, 880696.0, 881549.0, 686766.67, 832041.67, 961533.33, 1102425.0, 1166108.33, 1205958.33, 1316725.0, 1338009.09),
 (14, 'Indianapolis', 'Indiana', 821579.0, 827664.0, 835499.0, 844696.0, 850164.0, 853714.0, 859049.0, 863478.0, 870960.0, 876384.0, None, None, None, None, None, 131357.14, 139008.33, 150954.55),
 (15, 'Seattle', 'Washington', 610630.0, 622694.0, 635928.0, 653588.0, 670109.0, 687386.0, 709631.0, 728661.0, 742235.0, 753675.0, 380591.67, 405116.67, 425750.0, 465225.0, 529441.67, 619891.67, 694733.33, 687381.82),
 (16, 'Denver', 'Colorado', 603359.0, 620530.0, 635163.0, 649391.0, 664582.0, 683285.0, 696159.0, 704961.0, 716265.0, 727211.0, 196966.67, 255833.33, 264491.67, 303516.67, 338075.0, 373533.33, 414666.67, 421790.91),
 (17, 'Washington', 'District of Columbia', 605226.0, 619800.0, 634924.0, 650581.0, 662328.0, 675400.0, 685815.0, 694906.0, 701547.0, 705749.0, 361791.67, 452158.33, 474258.33, 496583.33, 512058.33, 525233.33, 520950.0, 547427.27),
 (18, 'Boston', 'Massachusetts', 621048.0, 630505.0, 642955.0, 653002.0, 662855.0, 670491.0, 679848.0, 687788.0, 691147.0, 692600.0, None, 418875.0, 441708.33, 489458.33, 523083.33, 566808.33, 612841.67, 639900.0),
 (19, 'El Paso', 'Texas', 650671.0, 664404.0, 674941.0, 674808.0, 677235.0, 676242.0, 679955.0, 681343.0, 679875.0, 681728.0, 133625.0, 127633.33, 125825.0, 125166.67, 126950.0, 132725.0, 137933.33, 146290.91),
 (20, 'Nashville', 'Tennessee', 604589.0, 612518.0, 625550.0, 635999.0, 645259.0, 655498.0, 661765.0, 663587.0, 667006.0, 670820.0, 141091.67, 157541.67, 171691.67, 185966.67, 208683.33, 233950.0, 256600.0, 271663.64),
 (21, 'Oklahoma City', 'Oklahoma', 582516.0, 590947.0, 600971.0, 612061.0, 621639.0, 632172.0, 639924.0, 642822.0, 647912.0, 655057.0, 95066.67, 112041.67, 116966.67, 129691.67, 132716.67, 134058.33, 133600.0, 147754.55),
 (22, 'Portland', 'Oregon', 585429.0, 595451.0, 604264.0, 609890.0, 620510.0, 631366.0, 642720.0, 647924.0, 650837.0, 654741.0, 260250.0, 287891.67, 307166.67, 330783.33, 369150.0, 396800.0, 416633.33, 420300.0),
 (23, 'Las Vegas', 'Nevada', 584576.0, 586606.0, 593275.0, 599551.0, 607976.0, 617487.0, 626538.0, 635262.0, 643228.0, 651319.0, 122091.67, 150508.33, 170091.67, 184691.67, 196850.0, 221083.33, 254250.0, 269200.0),
 (24, 'Memphis', 'Tennessee', 652326.0, 655341.0, 658786.0, 657146.0, 654990.0, 654106.0, 652548.0, 650878.0, 651104.0, 651073.0, 56725.0, 68041.67, 80975.0, 82741.67, 86241.67, 93925.0, 95866.67, 100781.82),
 (25, 'Baltimore', 'Maryland', 620915.0, 620410.0, 622895.0, 622391.0, 623587.0, 622522.0, 616226.0, 610481.0, 602443.0, 593490.0, None, 94400.0, 101975.0, 94383.33, 105766.67, 109525.0, 107683.33, 114627.27),
 (26, 'Milwaukee', 'Wisconsin', 594865.0, 597086.0, 598569.0, 599916.0, 600664.0, 600477.0, 596996.0, 593725.0, 591375.0, 590157.0, 88225.0, 77433.33, 85216.67, 96833.33, 104258.33, 113566.67, 123066.67, 131536.36),
 (27, 'Albuquerque', 'New Mexico', 546755.0, 552066.0, 555002.0, 557445.0, 557444.0, 557937.0, 559192.0, 559673.0, 559629.0, 560513.0, 169950.0, 166383.33, 170258.33, 174525.0, 178400.0, 183483.33, 190116.67, 204381.82),
 (28, 'Tucson', 'Arizona', 527160.0, 530709.0, 531880.0, 532945.0, 534800.0, 535607.0, 537528.0, 541377.0, 544858.0, 548073.0, 138033.33, 144291.67, 150541.67, 148225.0, 162308.33, 175475.0, 187850.0, 201136.36),
 (29, 'Fresno', 'California', 497769.0, 501429.0, 505414.0, 508880.0, 514100.0, 518203.0, 521426.0, 525373.0, 528814.0, 531576.0, None, 156666.67, 174200.0, 192833.33, 203575.0, 224408.33, 242558.33, 245427.27),
 (30, 'Sacramento', 'California', 467286.0, 470902.0, 474226.0, 478214.0, 482762.0, 488133.0, 494127.0, 500777.0, 507737.0, 513624.0, 136983.33, 173258.33, 203450.0, 226425.0, 253100.0, 271916.67, 298733.33, 315945.45),
 (31, 'Atlanta', 'Georgia', 429410.0, 437812.0, 449016.0, 453990.0, 461154.0, 468303.0, 479174.0, 491670.0, 498183.0, 506811.0, 118291.67, 147950.0, 177000.0, 198683.33, 201741.67, 208583.33, 219041.67, 244690.91),
 (32, 'Kansas City', 'Missouri', 460697.0, 462368.0, 464595.0, 467213.0, 470629.0, 475073.0, 481670.0, 488329.0, 492012.0, 495327.0, 101158.33, 109283.33, 117958.33, 131983.33, 137891.67, 163083.33, 174016.67, 183336.36),
 (33, 'Colorado Springs', 'Colorado', 420685.0, 427434.0, 432782.0, 438146.0, 442361.0, 449572.0, 458714.0, 465167.0, 472567.0, 478221.0, 172525.0, 187625.0, 195333.33, 210291.67, 226325.0, 247350.0, 275333.33, 295772.73),
 (34, 'Omaha', 'Nebraska', 459659.0, 462101.0, 465261.0, 468086.0, 470423.0, 472638.0, 475044.0, 476271.0, 477299.0, 478192.0, 126550.0, 130825.0, 133833.33, 141108.33, 148208.33, 156391.67, 169141.67, 186500.0),
 (35, 'Miami', 'Florida', 400779.0, 406593.0, 411149.0, 415661.0, 425110.0, 434738.0, 449149.0, 456617.0, 462819.0, 467963.0, 187083.33, 280350.0, 283025.0, 291016.67, 291575.0, 302258.33, 311116.67, 320245.45),
 (36, 'Virginia Beach', 'Virginia', 438859.0, 442583.0, 445044.0, 447706.0, 448864.0, 450304.0, 450983.0, 449896.0, 449849.0, 449974.0, 230225.0, 222341.67, 225016.67, 230858.33, 237533.33, 243000.0, 250991.67, 257263.64),
 (37, 'Tulsa', 'Oklahoma', 392403.0, 393005.0, 394643.0, 398401.0, 399892.0, 403491.0, 404007.0, 402060.0, 400414.0, 401190.0, 104058.33, 111725.0, 108191.67, 116141.67, 117716.67, 130266.67, 128108.33, 138618.18),
 (38, 'Tampa', 'Florida', 337053.0, 342589.0, 348090.0, 355172.0, 362664.0, 371464.0, 380344.0, 391026.0, 397232.0, 399700.0, 91683.33, 120308.33, 124891.67, 146175.0, 179375.0, 188750.0, 216225.0, 230727.27),
 (39, 'New Orleans', 'Louisiana', 347772.0, 360735.0, 369787.0, 378637.0, 383940.0, 389742.0, 391843.0, 391493.0, 391004.0, 390144.0, None, 160191.67, 162791.67, 175433.33, 175441.67, 185716.67, 188183.33, 207563.64),
 (40, 'Wichita', 'Kansas', 382745.0, 383773.0, 385751.0, 387210.0, 388416.0, 389412.0, 390519.0, 390277.0, 389231.0, 389938.0, 119866.67, 120816.67, 121866.67, 130566.67, 133608.33, 135641.67, 136966.67, 153036.36),
 (41, 'Bakersfield', 'California', 348987.0, 353221.0, 357312.0, 362834.0, 366954.0, 371348.0, 374699.0, 377940.0, 381714.0, 384145.0, 136733.33, 180383.33, 199983.33, 208016.67, 214950.0, 222716.67, 236191.67, 249663.64),
 (42, 'Cleveland', 'Ohio', 395926.0, 392667.0, 391550.0, 391792.0, 390871.0, 389244.0, 387662.0, 385252.0, 383214.0, 381009.0, None, 30008.33, 35641.67, 37316.67, 41841.67, 53408.33, 58075.0, 63263.64),
 (43, 'Stockton', 'California', 292888.0, 295363.0, 297045.0, 297493.0, 301062.0, 304550.0, 307158.0, 310143.0, 311628.0, 312697.0, 134216.67, 148041.67, 180325.0, 205900.0, 230291.67, 255625.0, 279275.0, 295963.64),
 (44, 'Cincinnati', 'Ohio', 296980.0, 296187.0, 296900.0, 297905.0, 298626.0, 299439.0, 299748.0, 301587.0, 302277.0, 303940.0, None, 115333.33, 125983.33, 129191.67, 143483.33, 140991.67, 148950.0, 154481.82),
 (45, 'Pittsburgh', 'Pennsylvania', 305283.0, 306012.0, 306355.0, 306902.0, 305964.0, 304070.0, 304643.0, 301494.0, 300570.0, 300286.0, 110025.0, 119250.0, 125625.0, 134050.0, 139175.0, 145483.33, 156516.67, 164645.45),
 (46, 'Greensboro', 'North Carolina', 269598.0, 272430.0, 276041.0, 279244.0, 282261.0, 284610.0, 289182.0, 291537.0, 294518.0, 296710.0, 121475.0, 120600.0, 125441.67, 131541.67, 134675.0, 133950.0, 145825.0, 158536.36),
 (47, 'Orlando', 'Florida', 239326.0, 243620.0, 249935.0, 255135.0, 262469.0, 270786.0, 278512.0, 281804.0, 285903.0, 287442.0, 88033.33, 131033.33, 147391.67, 162491.67, 181450.0, 199000.0, 232925.0, 242709.09),
 (48, 'Toledo', 'Ohio', 287065.0, 285425.0, 283185.0, 282352.0, 280712.0, 279898.0, 278897.0, 276688.0, 274864.0, 272779.0, None, 45281.82, 50366.67, 59258.33, 64358.33, 66858.33, 69033.33, 76372.73),
 (49, 'Fort Wayne', 'Indiana', 254161.0, 256293.0, 257626.0, 259333.0, 260570.0, 262109.0, 263513.0, 265128.0, 267460.0, 270402.0, 94500.0, 101616.67, 105458.33, 109633.33, 119966.67, 124133.33, 134375.0, 144645.45),
 (50, 'Madison', 'Wisconsin', 233730.0, 236908.0, 239880.0, 243233.0, 245848.0, 248788.0, 252677.0, 255786.0, 257854.0, 259680.0, 193814.29, 195391.67, 198891.67, 209658.33, 214641.67, 232200.0, 244075.0, 259272.73),
 (51, 'Reno', 'Nevada', 225652.0, 227061.0, 228926.0, 230987.0, 234096.0, 238082.0, 242143.0, 246615.0, 250146.0, 255601.0, 167075.0, 201291.67, 228391.67, 262208.33, 286850.0, 315658.33, 352083.33, 369681.82),
 (52, 'Richmond', 'Virginia', 204302.0, 206391.0, 210794.0, 213860.0, 217044.0, 220856.0, 225369.0, 227230.0, 229221.0, 230436.0, 143800.0, 172800.0, 177491.67, 181341.67, 202758.33, 200741.67, 208491.67, 215711.11),
 (53, 'Spokane', 'Washington', 209525.0, 209042.0, 209304.0, 210036.0, 211095.0, 212545.0, 215191.0, 217415.0, 219332.0, 222081.0, 147783.33, 145600.0, 142466.67, 153275.0, 164991.67, 175133.33, 195200.0, 224263.64),
 (54, 'Baton Rouge', 'Louisiana', 229374.0, 228643.0, 228889.0, 228346.0, 227851.0, 227202.0, 226686.0, 224414.0, 222190.0, 220236.0, 164408.33, 157733.33, 157733.33, 166958.33, 172658.33, 172091.67, 174916.67, 178481.82),
 (55, 'Modesto', 'California', 203301.0, 204017.0, 205040.0, 206075.0, 207652.0, 209245.0, 211231.0, 213000.0, 214389.0, 215196.0, 121041.67, 159025.0, 191125.0, 217200.0, 238191.67, 259666.67, 283033.33, 294963.64),
 (56, 'Des Moines', 'Iowa', 205032.0, 207924.0, 210244.0, 212026.0, 214350.0, 215243.0, 216308.0, 216662.0, 215994.0, 214237.0, 87308.33, 96550.0, 101616.67, 109633.33, 118408.33, 125966.67, 129000.0, 142900.0),
 (57, 'Grand Rapids', 'Michigan', 188007.0, 189104.0, 190821.0, 192982.0, 194335.0, 195056.0, 196556.0, 199135.0, 200136.0, 201013.0, None, 82616.67, 98141.67, 109733.33, 121616.67, 134725.0, 152183.33, 164281.82),
 (58, 'Huntsville', 'Alabama', 180941.0, 182327.0, 183748.0, 186001.0, 187834.0, 190333.0, 192412.0, 195420.0, 198125.0, 200574.0, None, 119958.33, 124408.33, 124641.67, 133725.0, 137933.33, 156658.33, 163354.55),
 (59, 'Salt Lake City', 'Utah', 186643.0, 188265.0, 190183.0, 192121.0, 191837.0, 192163.0, 194680.0, 200932.0, 200435.0, 200567.0, 209583.33, 234433.33, 245633.33, 259916.67, 273858.33, 299441.67, 328358.33, 361718.18),
 (60, 'Little Rock', 'Arkansas', 193972.0, 195292.0, 196564.0, 197143.0, 197595.0, 198178.0, 198631.0, 198314.0, 197484.0, 197312.0, 154791.67, 155383.33, 149933.33, 154083.33, 156266.67, 161616.67, 154566.67, 159309.09),
 (61, 'Mobile', 'Alabama', 194577.0, 193801.0, 193761.0, 193288.0, 192582.0, 191975.0, 191472.0, 190190.0, 189809.0, 188720.0, None, None, None, None, None, 118836.36, 136250.0, 132118.18),
 (62, 'Knoxville', 'Tennessee', 178258.0, 179955.0, 181093.0, 181779.0, 182631.0, 184046.0, 184986.0, 186905.0, 187362.0, 187603.0, 127308.33, 138008.33, 138216.67, 145966.67, 149433.33, 156591.67, 166641.67, 179727.27),
 (63, 'Worcester', 'Massachusetts', 181759.0, 182387.0, 182575.0, 183327.0, 184559.0, 184627.0, 184859.0, 185325.0, 185555.0, 185428.0, 163350.0, 164225.0, 167866.67, 180950.0, 194016.67, 205166.67, 221991.67, 240472.73),
 (64, 'Chattanooga', 'Tennessee', 170574.0, 172341.0, 173972.0, 175325.0, 175321.0, 176400.0, 177746.0, 179530.0, 181918.0, 182799.0, 108091.67, 117741.67, 121033.33, 136258.33, 142908.33, 152908.33, 157758.33, 172500.0),
 (65, 'Providence', 'Rhode Island', 178029.0, 178332.0, 178813.0, 178692.0, 179119.0, 179252.0, 179548.0, 179252.0, 179520.0, 179883.0, None, None, None, None, None, 195514.29, 202783.33, 208936.36),
 (66, 'Santa Rosa', 'California', 175238.0, 176243.0, 177093.0, 178684.0, 180585.0, 181485.0, 181909.0, 181596.0, 176750.0, 176753.0, 293925.0, 357600.0, 404583.33, 445433.33, 481266.67, 525741.67, 580791.67, 564590.91),
 (67, 'Salem', 'Oregon', 155247.0, 156171.0, 157369.0, 158814.0, 160675.0, 163175.0, 166478.0, 169627.0, 172646.0, 174365.0, 164050.0, 156591.67, 173875.0, 188041.67, 209250.0, 234633.33, 266300.0, 279272.73),
 (68, 'Springfield', 'Missouri', 159376.0, 160246.0, 161915.0, 163708.0, 164749.0, 166133.0, 166541.0, 167116.0, 167539.0, 167882.0, 108183.33, 110133.33, 114041.67, 119258.33, 124958.33, 128333.33, 136275.0, 141290.91),
 (69, 'Salinas', 'California', 150887.0, 152412.0, 153815.0, 154958.0, 155717.0, 156244.0, 156830.0, 156463.0, 155647.0, 155465.0, 228266.67, 303308.33, 353375.0, 386533.33, 424158.33, 453950.0, 483308.33, 506000.0),
 (70, 'Springfield', 'Massachusetts', 153569.0, 153773.0, 153933.0, 154056.0, 154376.0, 154582.0, 154028.0, 154207.0, 154329.0, 153606.0, None, 112075.0, 113408.33, 120775.0, 126966.67, 135050.0, 148675.0, 162527.27),
 (71, 'Killeen', 'Texas', 129024.0, 130838.0, 134240.0, 136294.0, 137589.0, 140147.0, 142854.0, 145149.0, 148683.0, 151666.0, 100033.33, 95283.33, 91308.33, 102516.67, 105325.0, 112241.67, 121725.0, 131590.91),
 (72, 'McAllen', 'Texas', 132093.0, 134639.0, 136277.0, 137421.0, 138719.0, 139909.0, 141888.0, 142249.0, 142530.0, 143268.0, None, None, 128100.0, 134408.33, 142125.0, 142425.0, 152175.0, 158881.82),
 (73, 'Syracuse', 'New York', 145215.0, 144526.0, 144414.0, 145044.0, 144331.0, 143816.0, 143176.0, 142287.0, 142745.0, 142327.0, None, None, None, None, None, 75222.22, 86650.0, 94837.5),
 (74, 'Charleston', 'South Carolina', 120700.0, 123012.0, 125223.0, 127246.0, 129434.0, 132413.0, 134453.0, 135626.0, 136111.0, 137566.0, 223375.0, 225158.33, 234575.0, 251891.67, 267191.67, 278858.33, 306225.0, 307763.64),
 (75, 'Columbia', 'South Carolina', 130774.0, 131302.0, 131761.0, 131527.0, 131781.0, 133616.0, 134129.0, 134005.0, 132770.0, 131674.0, None, 109625.0, 109391.67, 118791.67, 120525.0, 120491.67, 131666.67, 140663.64),
 (76, 'Lafayette', 'Louisiana', 121836.0, 122674.0, 123587.0, 124873.0, 126036.0, 126922.0, 127221.0, 126526.0, 126371.0, 126185.0, None, None, None, 162833.33, 163391.67, 167525.0, 167900.0, 173000.0),
 (77, 'Hartford', 'Connecticut', 125354.0, 125434.0, 125266.0, 125128.0, 124665.0, 124311.0, 123654.0, 122888.0, 122556.0, 122105.0, None, None, None, None, None, 97116.67, 113283.33, 137310.0),
 (78, 'Allentown', 'Pennsylvania', 118113.0, 118782.0, 118878.0, 118826.0, 119167.0, 120071.0, 120420.0, 121047.0, 121537.0, 121442.0, 116891.67, 98458.33, 98283.33, 104250.0, 111091.67, 119316.67, 132358.33, 138727.27),
 (79, 'Lansing', 'Michigan', 114321.0, 114559.0, 114661.0, 114734.0, 115093.0, 115324.0, 116569.0, 117730.0, 117931.0, 118210.0, 43291.67, 47400.0, 59416.67, 61208.33, 69550.0, 80525.0, 86683.33, 93090.91),
 (80, 'Manchester', 'New Hampshire', 109613.0, 110281.0, 110888.0, 111008.0, 111198.0, 111275.0, 111903.0, 112235.0, 112492.0, 112673.0, None, None, None, None, None, 211242.86, 225491.67, 231327.27),
 (81, 'Lakeland', 'Florida', 97640.0, 98834.0, 99000.0, 100326.0, 102034.0, 103550.0, 105837.0, 107712.0, 110421.0, 112136.0, 84208.33, 93841.67, 101216.67, 113375.0, 128025.0, 142525.0, 152125.0, 162509.09),
 (82, 'Albany', 'New York', 97753.0, 97956.0, 98409.0, 98488.0, 98366.0, 98232.0, 97941.0, 97735.0, 97011.0, 96460.0, 166025.0, 157250.0, 161508.33, 149916.67, 156966.67, 161675.0, 171258.33, 169418.18),
 (83, 'Asheville', 'North Carolina', 83459.0, 84457.0, 85321.0, 86355.0, 87837.0, 89374.0, 91123.0, 91748.0, 92630.0, 92870.0, 183975.0, 195683.33, 197725.0, 212741.67, 243525.0, 263308.33, 281500.0, 281181.82),
 (84, 'Santa Barbara', 'California', 88468.0, 88605.0, 89285.0, 90082.0, 90815.0, 91275.0, 91518.0, 91517.0, 91203.0, 91364.0, 745916.67, 758358.33, 882450.0, 893683.33, 955658.33, 987816.67, 1039416.67, 1078872.73),
 (85, 'Fayetteville', 'Arkansas', 73962.0, 75604.0, 76969.0, 78652.0, 80417.0, 82332.0, 83620.0, 85587.0, 86615.0, 87590.0, None, None, None, 177000.0, 178058.33, 187783.33, 207333.33, 215927.27),
 (86, 'Fort Myers', 'Florida', 62503.0, 63818.0, 65504.0, 67802.0, 70449.0, 73470.0, 76752.0, 80015.0, 82229.0, 87103.0, 93154.55, 134991.67, 149333.33, 168325.0, 167275.0, 174533.33, 198825.0, 206009.09),
 (87, 'Melbourne', 'Florida', 76363.0, 76537.0, 76854.0, 77393.0, 78276.0, 79323.0, 80656.0, 81822.0, 82603.0, 83029.0, None, 120400.0, 135700.0, 153225.0, 170783.33, 187916.67, 200766.67, 212563.64),
 (88, 'Greenville', 'South Carolina', 59414.0, 59810.0, 60171.0, 60625.0, 61505.0, 63606.0, 67134.0, 68474.0, 68849.0, 70635.0, 89991.67, 121291.67, 124075.0, 137375.0, 150050.0, 160175.0, 178016.67, 197063.64),
 (89, 'Daytona Beach', 'Florida', 61626.0, 61720.0, 62199.0, 62957.0, 63560.0, 64962.0, 67076.0, 68096.0, 68709.0, 69186.0, None, 77725.0, 81216.67, 99166.67, 110133.33, 120450.0, 138583.33, 133581.82),
 (90, 'Portland', 'Maine', 66088.0, 66183.0, 66216.0, 66391.0, 66832.0, 66825.0, 66911.0, 66646.0, 66405.0, 66215.0, None, None, None, None, None, 280928.57, 300600.0, 315400.0),
 (91, 'Youngstown', 'Ohio', 66876.0, 66556.0, 66056.0, 65470.0, 65142.0, 64687.0, 64335.0, 64540.0, 64860.0, 65469.0, None, None, None, 22871.43, 22708.33, 26325.0, 30416.67, 29781.82),
 (92, 'Sarasota', 'Florida', 52219.0, 52527.0, 52954.0, 53149.0, 54015.0, 54956.0, 56440.0, 57185.0, 57746.0, 58285.0, 145700.0, 167425.0, 187383.33, 205608.33, 226308.33, 240975.0, 247941.67, 257990.91),